### PR TITLE
Heroku

### PR DESCRIPTION
**Pull request by freeformz**
Prep for deployment to Heroku.
- Vendor the dependencies
- Procfile to declare process type
- app.json app description

### CODE REVIEW

**Comment by jipiboily** [comment]
I didn't review the code because I'm not a Go-pro (yet) but :+1: on the idea. If I can help make that happen, ping me!

**Comment by jipiboily** [comment]
@mdevan?

**Comment by mdevan** [comment]
Hi guys,

I'd love to include Heroku support, but would also like to keep mybot itself simple for people to play and experiment with. Is it possible to create a mybot-heroku repo, which will "import github.com/rapidloop/mybot" and add push-to-heroku support?

**Comment by freeformz** [comment]
@mdevan `github.com/rapidloop/mybot` is a main package and as such can't be imported (at least not with Go >= 1.5).

FWIW: In my eyes these changes make the project easier to play / experiment with  as it adds vendoring so builds will be repeatable. Those without the GO15VENDOREXPERIMENT flag set will just operate like normal.

**Comment by jipiboily** [comment]
No code was added to the bot, only library code right? Doesn't add any noise to the code and let you see running in a few seconds. I like this, but your call.

**Comment by mdevan** [comment]
So I tried merging freeformz/mybot heroku branch locally and pushing to Heroku, and this is what I got:

```
remote: -----> Go app detected
remote: -----> Checking Godeps/Godeps.json file.
remote: -----> Installing go1.5.1... done
remote: -----> Running: godep go install -tags heroku ./...
remote: slack.go:36:2: cannot find package "golang.org/x/net/websocket" in any of:
remote:     /app/tmp/cache/go1.5.1/go/src/golang.org/x/net/websocket (from $GOROOT)
remote:     /tmp/build_c14d3f08ae8ba0013cd1416fc4462adf/.heroku/go/src/github.com/rapidloop/mybot/Godeps/_workspace/src/golang.org/x/net/websocket (from $GOPATH)
remote:     /tmp/build_c14d3f08ae8ba0013cd1416fc4462adf/.heroku/go/src/golang.org/x/net/websocket
remote: godep: go exit status 1
```

What am I doing wrong? (I'm using go v1.4.2).

**Pull request closed without merging**
